# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - pre-deploy
  - deploy
  - post-deploy

image: python:3.9.2


lint:   
  stage: test
  allow_failure: true
  before_script:
    - pip install pylint smbus2
  script:
    - pylint input_proxy.py ./lib/*.py
  needs: []

mypy-type-check:
  stage: test

  before_script:
    - pip install mypy smbus2 types-PyYAML inputs luma.core
  script:
    - mypy .
  needs: []

sanity-check:
  stage: test

  before_script:
    - pip install PyYAML inputs smbus2
  script:
    - python3 input_proxy.py -c configs/dev -g configs/global-dev.yaml -l
  needs: []

.ssh:
  image: alpine:3.14
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --no-cache  openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOYMENT_SSH_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEPLOYMENT_TARGET_ID" >> ~/.ssh/known_hosts
  
deploy_stop_input_proxy_service:
  stage: pre-deploy
  extends: .ssh
  script:
    - ssh $DEPLOYMENT_TARGET sudo systemctl stop input-proxy
  allow_failure: true
  needs: [ ]

deploy_stop_ui_service:
  stage: pre-deploy
  extends: .ssh
  script:
    - ssh $DEPLOYMENT_TARGET sudo systemctl stop ui-service
  allow_failure: true
  needs: [ ]


deploy:
  stage: deploy
  extends: .ssh
  script:
    - >
      ssh $DEPLOYMENT_TARGET bash <<EOF
        sudo systemctl stop input-proxy || true
        echo first command
        echo second command
        cd /data/input_proxy
        pwd
        git reset --hard
        git checkout $CI_COMMIT_BRANCH
        git pull
        chmod +x input_proxy.py
        chmod +x ui_service.py
      EOF
  needs: [ deploy_stop_input_proxy_service, deploy_stop_ui_service ]]

deploy_start_service:
  stage: post-deploy
  extends: .ssh
  script:
    - ssh $DEPLOYMENT_TARGET sudo systemctl start input-proxy
    - ssh $DEPLOYMENT_TARGET sudo systemctl start ui-service
    - ssh $DEPLOYMENT_TARGET journalctl -u input-proxy -n 20
  needs: [ deploy ]
