from collections.abc import Generator
from typing import Any

valid_attributes: Any

def parse_str(text) -> Generator[Any, None, None]: ...
def strip_ansi_codes(text): ...
def find_directives(text, klass): ...
