from typing import List, Any

def get_choices(module_name): ...
def get_supported_libraries(): ...
def get_library_for_display_type(display_type): ...
def get_library_version(module_name): ...
def get_interface_types(): ...
def get_display_types(): ...
def get_transformer_choices(): ...
def load_config(path): ...

class make_interface:
    opts: Any
    gpio: Any
    def __init__(self, opts, gpio: Any | None = ...) -> None: ...
    def noop(self): ...
    def i2c(self): ...
    def bitbang(self): ...
    def spi(self): ...
    def gpio_cs_spi(self): ...
    def ftdi_spi(self): ...
    def ftdi_i2c(self): ...
    def pcf8574(self): ...
    def bitbang_6800(self): ...

class make_serial(make_interface): ...

def create_device(args: List[str], display_types: Any | None = ...): ...
def create_parser(description: str): ...
