class Error(Exception): ...
class DeviceNotFoundError(Error): ...
class DevicePermissionError(Error): ...
class DeviceAddressError(Error): ...
class DeviceDisplayModeError(Error): ...
class UnsupportedPlatform(Error): ...
