from collections.abc import Generator
from typing import Any

class diff_to_previous:
    prev_image: Any
    def __init__(self, num_segments: int = ..., debug: bool = ...) -> None: ...
    def redraw(self, image) -> Generator[Any, None, None]: ...

class full_frame:
    def __init__(self, **kwargs) -> None: ...
    def redraw(self, image) -> Generator[Any, None, None]: ...
