from threading import Thread
from typing import Any

class worker(Thread):
    tasks: Any
    daemon: bool
    def __init__(self, tasks) -> None: ...
    def run(self) -> None: ...

class threadpool:
    tasks: Any
    def __init__(self, num_threads) -> None: ...
    def add_task(self, func, *args, **kargs) -> None: ...
    def wait_completion(self) -> None: ...
