from typing import Any

unicode = str

class mutable_string:
    target: Any
    def __init__(self, value) -> None: ...
    def __getattr__(self, attr): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __len__(self): ...
    def __iter__(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class observable:
    target: Any
    observer: Any
    def __init__(self, target, observer) -> None: ...
    def __getattr__(self, attr): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __len__(self): ...
    def __iter__(self): ...

def from_16_to_8(data): ...
def from_8_to_16(data): ...
def unsigned_16_to_signed(value): ...
def bytes_to_nibbles(data): ...
