name: Pinball

devices:
  - name: HID 0838:8918
    index: 0
    bindings:
      - event: ABS_X
        address: 0x51
        invoke: LX
      - event: ABS_Y
        address: 0x51
        invoke: LY
    relative:
      - event: REL_X
        invoke: ABS_X
        mult: 1.5
      - event: REL_Y
        invoke: ABS_Y
        mult: 1.5
  
  - name: HID 0838:8918
    index: 1
    bindings:
      - event: BTN_Z
        address: 0x51
        invoke: R
      - event: BTN_TR
        address: 0x51
        invoke: ZR
      - event: BTN_THUMBL
        address: 0x51
        invoke: ZL
      - event: BTN_THUMBR
        address: 0x51
        invoke: L
      - event: BTN_EAST
        address: 0x51
        invoke: A
      - event: BTN_C
        address: 0x51
        invoke: B
      - event: BTN_NORTH
        address: 0x51
        invoke: Y
      - event: BTN_SOUTH
        address: 0x51
        invoke: X
      - event: BTN_TR2
        address: 0x51
        invoke: PLUS
      - event: BTN_TL
        address: 0x51
        invoke: MINUS
      - event: BTN_MODE
        address: 0x51
        invoke: HOME
      - event: ABS_HAT0X
        state: -1
        address: 0x51
        invoke: DPAD_LEFT
      - event: ABS_HAT0X
        state: 1
        address: 0x51
        invoke: DPAD_RIGHT
      - event: ABS_HAT0Y
        state: -1
        address: 0x51
        invoke: DPAD_UP
      - event: ABS_HAT0Y
        state: 1
        address: 0x51
        invoke: DPAD_DOWN
  
  - name: HID 0838:8918
    index: 2
    bindings:
      - event: BTN_Z
        address: 0x52
        invoke: R
      - event: BTN_TR
        address: 0x52
        invoke: ZR
      - event: BTN_THUMBL
        address: 0x52
        invoke: ZL
      - event: BTN_THUMBR
        address: 0x52
        invoke: L
      - event: BTN_EAST
        address: 0x52
        invoke: A
      - event: BTN_C
        address: 0x52
        invoke: B
      - event: BTN_NORTH
        address: 0x52
        invoke: Y
      - event: BTN_SOUTH
        address: 0x52
        invoke: X
      - event: BTN_TR2
        address: 0x52
        invoke: PLUS
      - event: BTN_TL
        address: 0x52
        invoke: MINUS
      - event: BTN_MODE
        address: 0x52
        invoke: HOME
      - event: ABS_HAT0X
        state: -1
        address: 0x52
        invoke: DPAD_LEFT
      - event: ABS_HAT0X
        state: 1
        address: 0x52
        invoke: DPAD_RIGHT
      - event: ABS_HAT0Y
        state: -1
        address: 0x52
        invoke: DPAD_UP
      - event: ABS_HAT0Y
        state: 1
        address: 0x52
        invoke: DPAD_DOWN
