from luma.core.device import device, parallel_device
from luma.core.virtual import character
from luma.oled.device.color import color_device
from luma.oled.device.framebuffer_mixin import __framebuffer_mixin
from luma.oled.device.greyscale import greyscale_device
from typing import Any

class sh1106(device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., **kwargs) -> None: ...
    def display(self, image) -> None: ...

class ssd1306(device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., **kwargs) -> None: ...
    def display(self, image) -> None: ...

class ssd1309(ssd1306): ...

class ssd1331(color_device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., framebuffer: Any | None = ..., **kwargs) -> None: ...
    def contrast(self, level) -> None: ...

class ssd1351(color_device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., framebuffer: Any | None = ..., h_offset: int = ..., v_offset: int = ..., bgr: bool = ..., **kwargs): ...
    def contrast(self, level) -> None: ...
    # def command(self, cmd: str, *args: str) -> None: ...

class ssd1322(greyscale_device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., mode: str = ..., framebuffer: Any | None = ..., **kwargs) -> None: ...
    # def command(self, cmd, *args) -> None: ...

class ssd1362(greyscale_device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., mode: str = ..., framebuffer: Any | None = ..., **kwargs) -> None: ...

class ssd1322_nhd(greyscale_device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., mode: str = ..., framebuffer=..., **kwargs) -> None: ...
    # def command(self, cmd, *args) -> None: ...
    def display(self, image) -> None: ...

class ssd1325(greyscale_device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., mode: str = ..., framebuffer: Any | None = ..., **kwargs) -> None: ...

class ssd1327(greyscale_device):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., rotate: int = ..., mode: str = ..., framebuffer: Any | None = ..., **kwargs) -> None: ...

class ws0010(parallel_device, character, __framebuffer_mixin):
    font: Any
    device: Any
    text: str
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., undefined: str = ..., font: Any | None = ..., selected_font: int = ..., exec_time=..., rotate: int = ..., framebuffer: Any | None = ..., const=..., **kwargs) -> None: ...
    def display(self, image) -> None: ...
    def get_font(self, ft): ...

class winstar_weh(ws0010):
    def __init__(self, serial_interface: Any | None = ..., width: int = ..., height: int = ..., **kwargs) -> None: ...
