name: Default

gamepads:
    address: 0x51
    devices:
    - name: usb gamepad
      bindings:
      - event: BTN_TOP2
        invoke: R
      - event: BTN_PINKIE
        invoke: L
      - event: BTN_THUMB
        invoke: A
      - event: BTN_THUMB2
        invoke: B
      - event: BTN_TOP
        invoke: Y
      - event: BTN_TRIGGER
        invoke: X
      - event: BTN_BASE4
        invoke: PLUS
      - event: BTN_BASE3
        invoke: MINUS
      - event: ABS_X
        state: 0
        invoke: DPAD_LEFT
      - event: ABS_X
        state: 255
        invoke: DPAD_RIGHT
      - event: ABS_Y
        state: 0
        invoke: DPAD_UP
      - event: ABS_Y
        state: 255
        invoke: DPAD_DOWN
    
