name: '002'
category: Default

devices:
  - name: usb gamepad
    index: 0
    bindings:
      - event: BTN_TOP2
        invoke: R
        address: 0x51
      - event: BTN_PINKIE
        invoke: L
        address: 0x51
      - event: BTN_THUMB
        invoke: A
        address: 0x51
      - event: BTN_THUMB2
        invoke: B
        address: 0x51
      - event: BTN_TOP
        invoke: Y
        address: 0x51
      - event: BTN_TRIGGER
        invoke: X
        address: 0x51
      - event: BTN_BASE4
        invoke: PLUS
        address: 0x51
      - event: BTN_BASE3
        invoke: MINUS
        address: 0x51
      - event: ABS_X
        state: 0
        invoke: DPAD_LEFT
        address: 0x51
      - event: ABS_X
        state: 255
        invoke: DPAD_RIGHT
        address: 0x51
      - event: ABS_Y
        state: 0
        invoke: DPAD_UP
        address: 0x51
      - event: ABS_Y
        state: 255
        invoke: DPAD_DOWN
        address: 0x51
  # - name: SINOWEALTH Wired Gaming Mouse
  #   bindings:
  #     - event: ABS_X
  #       address: 0x51
  #       invoke: LX
  #     - event: ABS_Y
  #       address: 0x51
  #       invoke: LY
  #   relative:
  #     - event: REL_X
  #       invoke: ABS_X
  #       mult: 1.5
  #     - event: REL_Y
  #       invoke: ABS_Y
  #       mult: 1.5
