from typing import Any

def textsize(txt, font: Any | None = ...): ...
def text(draw, xy, txt, fill: Any | None = ..., font: Any | None = ...) -> None: ...
def show_message(device, msg, y_offset: int = ..., fill: Any | None = ..., font: Any | None = ..., scroll_delay: float = ...) -> None: ...
