name: Global
category: Default
i2c_device: 1
display:
  addr: 0x8
  icon: 0x3

menu:
  event: BTN_MODE
  device: 
    name: HID 0838:8918
    index: 1
    bindings:
    - event: ABS_HAT0Y
      state: 1
      invoke: NEXT_CONFIG
    - event: ABS_HAT0Y
      state: -1
      invoke: PREV_CONFIG
  