name: Global
category: Default
i2c_device: 1

menu:
  event: BTN_BASE4
  device: 
    name: usb gamepad
    index: 0
    bindings:
    - event: ABS_Y
      state: 255
      invoke: NEXT_CONFIG
    - event: ABS_Y
      state: 0
      invoke: PREV_CONFIG
    - event: BTN_BASE3
      invoke: TOGGLE_WIFI
  