from typing import Any

class bitbang_6800:
    def __init__(self, gpio: Any | None = ..., pulse_time=..., **kwargs) -> None: ...
    def command(self, *cmd) -> None: ...
    def data(self, data) -> None: ...
    def cleanup(self) -> None: ...
